MsgHdr.hsc: fix field 'struct msghdr::msg_namelen' size
msg_namelen has a 'socklen_t' type on linux (always 32 bits).
Using CSize there breaks 64-bit BE platforms.

  testSendManyTo: [Failed]
       ERROR: sendmsg: invalid argument (Destination address required)

Caught by testSendManyTo test on ppc64:

Gentoo-bug: http://bugs.gentoo.org/436640
Reported-by: Anthony Basile <blueness@gentoo.org>
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>